### ISSUE TITLE
Rewrite user profile in React

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1019]
This is a roadmap for rewriting user's profile in React.
All the functionality should survive this.
Design should survive this.

### Routes

```
/profile/:username
/....../........./overview
/....../........./accomodation
/....../........./contacts
/....../........./references
```
#### Routing

Let's implement routing within the profile with e.g. [`react-router`](https://github.com/ReactTraining/react-router).

### Components

Components in Angular to rewrite in React. Break down to subcomponents.

`/modules/users/client/views/profile/` -> `modules/users/client/components/`
- [ ] **[TODO]** `./profile-view.client.view.html`
  - eventually only this one should be imported to AngularJS
- [ ] **[TODO]** `./profile-view-tribes.client.view.html`
- [ ] **[TODO]** wrap #1058 #1059 and #1060 together (completely replace `profile/profile-view-basics.client.view.js`)
- [ ] **[WIP]** `./profile-view-accommodation.client.view.html`
  - [ ] **[WIP]** Offers `/modules/offers/client/views/directives/tr-offer-host-view.client.view.html` (#1045 @agatatalita) 
  - [x] Location (#1023 @mrkvon) 
- [x] **[WIP]** References (@mrkvon) 
- [x] **[DONE]** Avatar and Name for small screen (#1058 @mrkvon)
- [x] Panel for Avatar, Modal with Avatar and ProfileViewBasics (#1060 @mrkvon)
- [x] **[WIP/DONE]** `./profile-view-references.client.view.html` (@mrkvon #918)
- [x] Report Member link (#1059 @mrkvon)

- [x] Contacts in common (#1026 @RGHuynh)
- [x] Contact List (#1017 @mrkvon)
- [x] About `./AboutMe.component.js` (#1005 @agatatalita) 
- [x] Profile View Basics `./ProfileViewBasics.component.js` (#1000 @agatatalita)
- [x] Avatar (#997 @mrkvon)

We can also consider a file structure independent from MEAN.

#### How to get there

First, we need to replace the components one by one and wire them to Angular. (top-down: starting with leaf components and then get deeper to Angular)
Then, we can wire them together to one React (sort of) module with a router and a state.

Alternatively, we can create a feature branch for this and work bottom up. Set up a router and then build leaves.
#### Bootstrap
At the moment we are using react-bootstrap 0.32.4 working with Bootstrap 3. Documentation to that version can be found [here](https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/getting-started/introduction/).

### State

Redux

### i18n

All (presentational) components should be translatable.

### Data Fetching

All data will be fetched via React. We'll provide only authenticated user from Angular.

**Comment by RGHuynh** [comment]
@mrkvon I would like to help out with building some of those components. I do have a React background.

**Comment by mrkvon** [comment]
@RGHuynh 
Great!
Do you have a preference which part you would like to tackle?

I think @agatatalita was going to work on Tribes panel in profile.

There are a few things that are next to do I can think of:
- Contacts in common `./modules/contacts/client/directives/tr-contacts-common.client.directive.js`. Perhaps `Contact` component of #1009 could be reused here.
- Breaking down components to reusable pieces that can be implemented separately (Then more things to do will appear.).
- Location (the little map showing the user's hosting offer) (Perhaps using `react-leaflet` library. I'm starting to look into that. If you'd like to take it over, let me know.)
- Navigations from `./modules/users/client/views/profile/profile-view.client.view.html`

Once we have these building blocks migrated, we can tackle the routing and state. It's a work in progress and things will be changing.

Independent from this module, there are many pages in `modules/pages/client/views/` which will get migrated. Perhaps you'd like to tackle some of them. It's a work which has less dependencies, so possibly less hectic, more predictable.

We'll be figuring things up as we progress. For more informal discussion let's connect on trustroots slack or other channels. :slightly_smiling_face: 

I'll be moving in coming days, so I will be hard to reach for some time.

**Comment by simison** [comment]
> In my opinion we should tackle this one first and establish some structures and good practices before starting them.

💯 this. We can get more done faster together if more folks work over the same piece of code, too.

Tribes panel, user description, hosting description and contacts in common would benefit from generic "Show more" component:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/87168/50549805-ff8d6000-0c6b-11e9-964d-ec9fb9a583d8.png">

**Comment by RGHuynh** [comment]
I can work on the sign in page components.

**Comment by mrkvon** [comment]
@RGHuynh 
I guess parts of my post may have had confusing information. It may have suggested that _Sign in_ has a priority (which it doesn't). I updated it as follows:

> Then there is search, profile-edit, sign up, sign in... .
> In my opinion we should progress with migrating the user profile first and establish some structures and good practices before starting those.

Of course you're still very welcome to work on sign in, if that's what you'd like to do. :slightly_smiling_face:

I guess the presentational part will be more or less stable. (+ DRYing and breaking down to reusable subcomponents.) Logic will be changing as we replace Angular with React more deeply.

**Comment by RGHuynh** [comment]
@mrkvon 
My bad I think miss understood that part.

I can work on this part.
>Contacts in common ./modules/contacts/client/directives/tr-contacts-common.client.directive.js. Perhaps Contact component of #1009 could be reused here.

**Comment by mrkvon** [comment]
Sure! :+1:

**Comment by RGHuynh** [comment]
@mrkvon For the contacts common list component. Is there a way to see it in localhost when I signed in to Admin?

**Comment by mrkvon** [comment]
We don't have the contacts populated with `npm run seed`. You'll need get an access to at least 3 different accounts and create + confirm a contact at least between two of them.

```
(user1) ---[contact]--- (user2) ---[contact]--- (user3)
```

Then sign in as _user1_ and open profile of _user3_. _User2_ should be your contact in common.

Or you can add the data in mongodb directly. (Needs additional research.)

If you created your data with `npm run seed`, you have 3 users: `admin1`, `admin2`, `admin3` with password `password123`.

To create or access any other users, you can access emails in MailDev client, which is running at your [localhost:1080](http://localhost:1080) by default. Then you can verify email address of a new user or ask for password reset of any existing user.
