### ISSUE TITLE
Useful admin tools to support our members

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1079]
To support our members better and to keep the community safe from abusers and spammers, we need easy to use and secure support tools. (See also Roles #767.)

We now have some, here are more ideas. Feel free to modify this list directly instead of adding comments to the thread:

- [x] Search users by name, email and username
- [x] Observe user profile data, including suspended users
  - [ ] Observe support requests from or related to user
  - [ ] Ability to add notes about profile https://github.com/Trustroots/trustroots/pull/1540
- [x] Read messages between two members (we ask for consent)
- [ ] Observe number of messages/threads the user has written
- [x] Ability to suspend and shadow-ban member easily
  - [x] suspending should also hide the profile
  - [ ] buttons to remove user roles again https://github.com/Trustroots/trustroots/issues/2555
- [ ] Highlight detected spammers in some dashboard #1074 
- [ ] An auto-warning when somebody hits some threshold of negative ratings on their messages #781
- [ ] Ability to send user email & password confirmation emails or extend previously generated keys
- [ ] Masquerading #670 (especially great for debugging rare issues related to database, would also replace some of the other features on the list but at the same time, this is potentially very complex instead of debugging locally with identical database entry)
- [ ] Show count of "messages in the spirit of TR" in member report card (e.g. "17/20")
- [ ] Repair or remove Zendesk search link

Please add comments on what you feel should be higher priority tool to build or if something isn't really needed. Would be good to gather what is "a must" and what is "nice to have".

Note that all the admin tool actions are audit logged.

cc @guaka @doktorhorst @noahsmindfuck

**Comment by doktorhorst** [comment]
That's great and makes support stuff much faster.
I'd say in a lot of report cases, it might be very useful to look into *more* messages sent by the reported member, not only the ones to the reporting member. But idk if that is ok with our privacy approach.

**Comment by guaka** [comment]
Yes. Maybe we should divide this process into several steps.

There have been a couple of cases where the reporter looks like the offender. So we can start by getting the reporter's permission to read their messages, and if we need more we go ahead and also read the other party's messages, possibly only with their permission.

Maybe part of reporting a member is that you agree (with a checkbox) to have the support team read messages you sent to that reported member?

(It's tricky and complicated.)

**Comment by noahsmindfuck** [comment]
I am happy to hear that this kind of tools are under development but I have no idea how to access what is already there. So far I am able to use the zendesk-Platform and I know that I subscribed to the slack channel. But how would I search for username/email,... or observe user data.. whatever is mentioned with a checked checkbox? :)

**Comment by simison** [comment]
@noahsmindfuck I made you an admin so you should be able to see https://www.trustroots.org/admin now.

**Comment by doktorhorst** [comment]
Aquisition stories are nice (latest 1000), but it could be even more interesting to be able to search for strings in all of them

**Comment by simison** [comment]
I can just make the limit something like 10K and you can use browser search to search stuff. :-)

**Comment by doktorhorst** [comment]
Not really important, but I would be interested in the statistics. If it's doable without a lot of effort, an exported csv file of the ones until today would be even more comfortable.

**Comment by simison** [comment]
Oh yeah, I think that's what I should've done initially actually.

Are you interested in counts of specific words?

**Comment by doktorhorst** [comment]
Yup, and fiddle around with what's there. Look for trends over time
