### ISSUE TITLE
Master issue for search members frontend

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#1152]
Follow up of #965 and #530. Related issue for backend support: #944

- [ ] Add pagination to the results
- [ ] In the results list, hhow other info like living location, language, gender, last seen,..
- [ ] Use query parameters after `search?=` to populate initial search

To discuss:
- [ ] Fuzzy search (?Think about it). Take admin search as an example: #960
- [ ] Add a link from the /profile/<username>/contacts page to /search/users (? Related: #1020 and #1031)
