### ISSUE TITLE
Set up JavaScript error tracking to production

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1197]
- [x] Create TR account at https://sentry.io/pricing/ (@simison)
- [x] Share account with @nicksellen and anyone else interested  
- [ ] Add scripts to the app, remember to add domains to [CSP headers](https://github.com/Trustroots/trustroots/blob/a2e3ba06f3dd0abf1661b48ce6dd9da7a1eb4bfd/config/lib/express.js#L221) https://github.com/Trustroots/trustroots/pull/1264
- [ ] check sensitive information won't be sent to sentry (e.g. passwords)
- [ ] Add to `/docs`
