### ISSUE TITLE
[Overview] React migration

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1334]
_This is an issue to organize a bigger picture of React migration. It should serve as overview of the work and crossroad to more specific topics_

- To add something to this issue, please edit this description directly, if you can.
- Inform us on slack or in comments or edit the issue to grab things you want to work on
- Add [`React` label](https://github.com/Trustroots/trustroots/labels/react) to any issue or PR you may open that is related to React migration.
- Add your stuff to [Framework refactor](https://github.com/Trustroots/trustroots/projects/4) project, too.

### Components to migrate:

_this should be broken down into subtasks and completed more, maybe in separate issues_

Here's the list of our modules:

#### admin

**DONE** already implemented in react

#### core
- [x] 404 https://github.com/Trustroots/trustroots/pull/1957
- [ ] [Push notification question](https://github.com/Trustroots/trustroots/blob/2b57c46fafd9b48015dd253d07a383283ecfdfb0/modules/core/client/views/push-notification-question-modal.client.view.html)
- [x] [Header](https://github.com/Trustroots/trustroots/blob/86f9c2d88dd52e7fdfa9062cda915c1548ac5343/modules/core/server/views/partials/header.server.view.html) WIP PR: https://github.com/Trustroots/trustroots/pull/2171
- [ ] [Footer](https://github.com/Trustroots/trustroots/blob/86f9c2d88dd52e7fdfa9062cda915c1548ac5343/modules/core/server/views/partials/footer.server.view.html)

#### messages

- [x] inbox #1171 (@nicksellen)
- [x] threads #1173 (@nicksellen)
- [x] unread messages counter https://github.com/Trustroots/trustroots/pull/1370 (@nicksellen)
- [x] reference question next to message thread (aka references-thread)  https://github.com/Trustroots/trustroots/pull/1978

#### offers

- [ ] **TODO** Meetup pages (https://www.trustroots.org/offer/meet)
- [ ] **WIP** Host offer #1301 
- [x] Hosting & meet map https://github.com/Trustroots/trustroots/pull/1156

#### pages

- [x] (modules/pages/client/views) https://github.com/Trustroots/trustroots/pull/1412

#### Experiences

- [x] Implemented in react from the start

#### search

- [x] map  https://github.com/Trustroots/trustroots/pull/1329
- [ ] map sidebar, WIP: https://github.com/Trustroots/trustroots/pull/1971

#### statistics
- [x] https://github.com/Trustroots/trustroots/pull/1959

#### stats

- [x] `/statistics` page https://github.com/Trustroots/trustroots/pull/1959

#### support

- [x] Support page + form https://github.com/Trustroots/trustroots/pull/1994

#### circles

- [ ] **TODO** A single circle page (e.g. https://www.trustroots.org/tribes/hitchhikers) WIP: https://github.com/Trustroots/trustroots/pull/2233
- [x] **DONE** circles page #1133 

#### users

- [ ] Edit profile & account (https://www.trustroots.org/profile/edit)
  - [ ] Basics
  - [ ] Locations
    - [ ] Location inputs WIP: https://github.com/Trustroots/trustroots/pull/2614
    - [x] Hosting & Meet https://github.com/Trustroots/trustroots/pull/2172
  - [ ] Photo
  - [ ] Networks
  - [ ] Account
      - [ ] Email
      - [ ] Notifications
      - [x] Interface language
      - [ ] Change your password
      - [ ] Username
      - [x] Download your data https://github.com/Trustroots/trustroots/pull/1966
- [ ] **WIP** #1019 User profile

### application architecture topics

- [ ] data layer discussion https://github.com/Trustroots/trustroots/issues/1416
- [ ] routing architecture
