### ISSUE TITLE
[Overview] i18n / translations

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#1485]
We made a lot of progress with i18n since the [original discussion](https://github.com/Trustroots/trustroots/issues/492), but still some threads to draw together to get it finally up and running:

- [x] work out how and when to extract the translations from the source (see https://github.com/Trustroots/trustroots/issues/1486)
- [x] work out how to incorporate the changes back from Weblate (see https://github.com/Trustroots/trustroots/issues/1487)
- [x] make/fix/update/tweak the language selecting flow (maybe it's fine, but lets check! it's enabled on https://dev2.trustroots.org/ (but don't expect to see all the language content)
- [ ] update guide from dev perspective (https://team.trustroots.org/i18n.html) (see https://github.com/Trustroots/community/issues/87)
- [x] create/update guide from translator perspective (is pretty much ready --> https://team.trustroots.org/Translating-Getting-Started.html - just awaiting some review, ask Martin in slack) -- still needs to be updated?
- [ ] make the rest of the site content translatable
   - [ ] Clientside translations depend on React migration. See #1334
   - [ ] Server side translations (mostly emails & error messages)
- [x] Support Right-To-Left (RTL) languages like Hebrew.
