### ISSUE TITLE
[Overview] Experiences

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#1493]
This is to summarize current state of references work and the steps we need to complete to get it ready for us.

## A bit of history / context

(pre-history, [a mention](https://ideas.trustroots.org/comparison-of-hospitality-exchange-platforms/#comment-14932) that _we’ve been working on a reference system for a while already._ ... in 2016).

The topic has been around for a long time with a lot of discussion, this is the [original discussion](https://github.com/Trustroots/trustroots/issues/718) created in October 2018. A bunch of the people commenting in that issue are not active any more. I consider it a piece of history by now. Although with some nice discussions on it.

@mrkvon actually implemented most of the references as described in that issue, but got stuck when it needed a bit more design/discussion input. It's been in the code for a while now in an incomplete state, but hidden behind a feature flag (turned off on https://trustroots.org and on on https://dev2.trustroots.org).

At the hackweek (April 2020) we discussed references again, to try and bring it back to life (see [meeting minutes](https://wiki.trustroots.org/en/Meeting_Minutes/2020-04-13_Hackweek_-_references_session) from that session).

We got a bunch of further work done based on those discussions, and some merged. But it stalled again after that ([this slack thread](https://trustroots.slack.com/archives/C08SENA9Z/p1587373767234900) was the last we heard about it).

Another sprint of work is happening in August 2020.

## TODO Non Technichal

- [x] See if https://github.com/Trustroots/trustroots/pull/918 has something to salvage 
- [x] See if https://github.com/Trustroots/trustroots/pull/1389 has something to salvage
- [x] Display user references (`/profile/USERNAME/references`) (overview https://github.com/Trustroots/trustroots/issues/1494)
  - [x] Basic skeleton for listing references (https://github.com/Trustroots/trustroots/pull/1662)
    - [x] Work on improving visuals for the list (@hlibbabii takes a look, we are not sure what this means)
    - [x] Hide "Write one!" nudge when looking at own profile and there are no references (https://github.com/Trustroots/trustroots/pull/1668)
    - [x] remove colors from the top-heading counters (positive/negative/maybe)

- [x] Write references.
    - [x] Basic functionality implemented (`/profile/USERNAME/references/new`)
    - [x] Update questions, Update possible answers to questions (ask non-tech people to help with this) (#1856 )

    - [x] Test if "support" feature (when adding "no" reference) works and if not, implement/fix (the email shows in MailDev)

    - [x] Change "Success sending reference" green box to something more celebratory and appealing, now it looks pretty technical **(design needed)**
- [x] Add a script to populate test DB with experiences: https://github.com/Trustroots/trustroots/issues/1669
- [ ] Update email texts if needed ([one](https://github.com/Trustroots/trustroots/blob/master/modules/core/server/views/email-templates-text/reference-notification-second.server.view.html) [two](https://github.com/Trustroots/trustroots/blob/master/modules/core/server/views/email-templates-text/reference-notification-first.server.view.html)) see [suggestions](https://codi.kanthaus.online/ml-references-feedback) (Trustroots/community#88) (non-technical)
- [x] Look into `hostedMe`/`hostedThem` vocabulary if it can be made easier to understand with `guest`/`host` terms (#1843 ) (non-technical)
- [x] Decide if feedback field needs to behave differently in different scenarios (#1861 tech side complete, non blocker for Chagai)
- [ ] Work on announcement blog post & social media blurbs ([Slack](https://trustroots.slack.com/archives/CT5U2RCH3/p1597495440014100)
- [ ] Deploy to prod and enable feature flag! 🎉 

#### UI Design
- [ ] content policy, especially personal information that one would want to keep private. Also support-team options for hiding problematic content
- [ ] Follow-up notification if experience was not shared within 11 days
- [x] add gender to profile name on the references list (#1841)
- [ ] when looking at my references, show which ones I gave and they’re still private (and time left) (#1842) (more like a feature, as experiences this is very important to keep users aware of the fact that their experiences are meant for them)
- [x] show list of references which user gave (aka replies) https://github.com/Trustroots/trustroots/issues/1686 (Chagai thinks this could perhaps be released on a second iteration)
- [x] Add count of public references to "References" tab in the profile (#1840) PR https://github.com/Trustroots/trustroots/pull/1970
- [x] Change "You've already left them a reference" yellow box to something more appealing **(design needed)** (non blocker for Chagai - Feature Request - easy first task)
- [ ] Hide or disable "Write reference" link
- [x] Show the reference you've left to them
- [ ] Check the length of experience text and maybe limit it for UI purpose?
- [ ] Displaying of long lists of references and filtering of it
- [ ] Decide on a reasoning for using percentage vs. absolute numbers and what that means for members who read them, also how to deal with parts of summary that we don't show
- [ ] change Member since date to "registered X years ago"
- [x] use "Skip" instead of "I don't know"
#### Others
- [ ] Add component tests (Chagai thinks this is a lower priority and should be listed elsewhere)
- [ ] when looking at my references, show which ones I haven’t given back (public or private) and how much time is left till they become public. Provide a button. 
- [ ] "No" in recommendations is currently not accepted and leads to a "greenwashing" of experiences. Encourage members to speak about it if they didn't like their experience without it being a judgement for the person who the experiences was with. As we are all different this is a totaly valid and qualitatively positive thing.
- [ ] make tags (Host, Guest, recommend, ...) clickable and put them on the top right for better skimmability
- [ ] editability of experiences
- [ ] adding guidance - not only for experiences ;)

**Comment by collector** [comment]
I'm new to this discussion but believe that hearing me out can greatly benefit the safety of members on TrustRoots. I'm the founder of a social network for collectors called Colnect and have been an avid traveler for year and hosted as well. On Colnect, collectors around the world exchange with one another and this create a good ground for cheaters. We have thus improved our community safety with years of experience and understanding of the costs to a community's reputation whenever a single member suffers a problematic event. While on Colnect, the biggest damage can be monetary loss, on hosting platforms there have been physical assaults. My suggestions here have never been implemented on CS nor BeWelcome and I believe this is the reason references generally suck all around.

As everyone here probably understands the concept of references and the purpose of them improving community safety, I'll simply go directly to the suggestions:
1/ Do NOT let new accounts write a reference. There should be minimal requirements for writing a reference. Without minimal requirements, it's super-easy to create multiple accounts and have them start writing references to one another. This is NOT a theoretical thing but something which has happened to us on Colnect. Some possible minimal requirements:
a. profile exists for at least 30/60/90 days and logged in at least 10/20/30 times and/or viewed at least 100/500/1000 pages
b. profile has received at least 1/2/3 references/friend add from others. This is the "circle of trust".

2/ References should be DOUBLE-BLIND so people won't be afraid to say what they really felt.

3/ References may be left only 3 days AFTER the hosting have occurred. I personally know of some creepy hosts that have asked people for a reference at the beginning and then misbehaved.

4/ Leaving a reference should be mandatory when there has been hosting. So within 3-21 days after the hosting it's optional and afterwards the person MUST leave a reference of the encounter. I personally know of creepy experiences that weren't reported as the victim was either afraid or chose to avoid conflict. In such a case, one can easily read between the lines of a "positive" experience to see it's actually been problematic.

5/ The process should ask clear questions rather than choose: positive/negative and add a few words. Questions such as:
a. Have you physically met the person?
b. Did you feel safe with that person?
c. Did you feel comfortable with that person?

Hoping this helps, your feedback welcome :)

**Comment by hlibbabii** [comment]
I can do "Hide "Write one!" nudge when looking at own profile and there are no references".

**Comment by simison** [comment]
@hlibbabii yap! Thanks. 

As a pointer, you can pass current authenticated user to the component in here:
https://github.com/Trustroots/trustroots/blob/5b4b1f8e65c14e4ddc878fc1bf8b68b2f58bb620/modules/users/client/config/users.client.routes.js#L381

Like this:

https://github.com/Trustroots/trustroots/blob/5b4b1f8e65c14e4ddc878fc1bf8b68b2f58bb620/modules/users/client/config/users.client.routes.js#L391

...so maybe `authenticatedUser="app.user"`. That's Angular directive/React component boundary so it might seem a bit exotic, but all you really need to worry then is what to do with it inside the React component. ;-)

**Comment by chagai95** [comment]
We just tested and reporting to moderator seems to work fine, also emails and references showing on users profile seem to work as well.
