### ISSUE TITLE
Webpack build todo

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#791]
- [ ] put gulp in fire
- [ ] style (css/less) via webpack
- [ ] add hot (module) reloading
- [ ] maybe use some cooler webpack options (splitting, etc) to make it suitable for production deployment
- [ ] reimplement `uib-templates.js` / `templates.js` building via webpack loader
- [ ] consider extracting and abstracting dependencies for legacy libs ([example from fs.de](https://gist.github.com/nicksellen/569a54762e9c2343cf27ffe15682a1aa))
- [ ] move away from massive lists of files in `config/assets/*`
- [ ] actually use js modules (currently all the actual `modules/*` files are written as if they are global) - can probably use some [webpack contexts](https://webpack.js.org/guides/dependency-management/) for globbing
- [x] add es6 loader to webpack
- [ ] add at least 300 webpack plugins so computer can be used as heater in the coming winter
