### ISSUE TITLE
emails might end up in spam

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#96]
happened to Erga

looks fine:
* http://mxtoolbox.com/domain/trustroots.org/?source=findmonitors
* `trustroots.org.		86400	IN	TXT	"v=spf1 include:spf.mandrillapp.com ?all"`

to do:
- [x] add warning #14 
- [x] plain text versions #92
- [x] include recipient's name at To field, not only email
- [ ] include "unsubscribe" word into emails
- [ ] add support info at email footer #190 
- [ ] add contact info at email footer #189
- _...anything else?_

**Comment by simison** [comment]
Humm! I just realised no-reply@ doesn't exist currently. @chmac 

On the other hand [this article](http://www.gettingemaildelivered.com/do-not-use-noreply-or-dontreply-as-your-from-return-address-in-email) suggests we should use something else. Thoughts/experiences?

We're obviously not going to collect no-reply mails anywhere but dev/null anyway. Bounce errors we would get from Nodemailer once we implement them properly.

**Comment by guaka** [comment]
otherwise, to get around the "marked as spam", use e.g.
kasper@trustroots.org for a while and forward that to my G inbox, I'll
filter and label it and check it once a day, if this improves the spam
situation by the end of the month we can move towards noreply@

**Comment by simison** [comment]
@chmac @guaka does that forwarder already exist & can I switch to that right away?

**Comment by chmac** [comment]
I believe mail hits my mail host. If you want an alias configured and forwarded somewhere, just let me know what @ and where you want it to go...

**Comment by simison** [comment]
@chmac: kasper@ —> Kasper's Gmail. :-)

**Comment by chmac** [comment]
Done.

I also added Mikael to the forward for hello@ which I realise wasn't going to you previously. Hope I didn't miss any messages in there assuming you would answer them...

**Comment by chmac** [comment]
Whoops, realise this issue was not only about creating email aliases.

**Comment by simison** [comment]
@chmac I don't think hello@ was written down anywhere publicly earlier anyway?

**Comment by simison** [comment]
Looks like kasper@ as "from" address works better for spam stuff compared to noreply@. Interesting!

Let's change it to something more generic one that we'd also keep checking since people seem to sometimes reply mails directly for support. Additionally I'll add support contact more visibly to mails #190

hello@, from@, notification@, or ping@ — what do you think?

**Comment by guaka** [comment]
I don't get that many emails, I'm totally fine with average of less than 1 per week.

I like hello@trustroots.org.

**Comment by simison** [comment]
@chmac, hello@ is forwarded for us three?

**Comment by guaka** [comment]
"Unsubscribe kasper@trustroots.org from LinkedIn invitation reminders?" yes! :)

**Comment by chmac** [comment]
Just changed hello@ to reach all 3 of us. Going to be tricky to track how we reply. Maybe worth one of those online ticket type things? Or a single gmail account that we all log into from? Or we always CC the hello@ address when we reply? Or we solve the problem when we have it? :-)

**Comment by guaka** [comment]
with hitchwiki we cc contact@hitchwiki.org most of the time, has worked
well enough the past years :)

**Comment by simison** [comment]
I changed from-address to "hello" at production.

Yep, CC'ing works fine.

In any case you can expect me to be able to solve most of the support mails (they often need checking something from the DB), so you can wait for a few hours before replying them. Support mails from WP come now only to me.

I want to install some support/ticket thingy anyway just because it'd be so much easier to follow easier which mails I have replied and to have some basic reply templates at handy etc. #106

**Comment by simison** [comment]
http://mxtoolbox.com/domain/trustroots.org/?source=findmonitors 
now gives:

>**Hostname has returned a SPF Record that has been deprecated**

>The use of alternative DNS RR types that was formerly supported during the experimental phase of SPF was discontinued in 2014. SPF records must now only be published as a DNS TXT (type 16) Resource Record (RR) [RFC1035]. See RFC7208 for further detail on this change.

>According to RFC 7208 Section 3.1: During the period when SPF was in development, requirements for assigning a new DNS RR type were more stringent than they are today and support for the deployment of new DNS RR types was not deployed in DNS servers and provisioning systems. The end result was that developers of SPF discovered it was easier and more practical to follow the TXT RR type for SPF.

I'll look into it today.

**Comment by chmac** [comment]
I think the problem is that both of these commands return the same, but the second one should not return anything, as SPF as a type of records has been deprecated. So instead of having types like MX, and SPF, and TXT, it's now just TXT which contains an SPF string.

```
➜  ~  dig +short txt trustroots.org
"v=spf1 include:spf.mandrillapp.com ?all"
➜  ~  dig +short txt trustroots.org
"v=spf1 include:spf.mandrillapp.com ?all"
```

**Comment by chmac** [comment]
I guess the solution is just to remove the type=SPF record from the DNS server. Not sure who controls DNS though, maybe @guaka ?

**Comment by simison** [comment]
@chmac I removed type=SPF record now, thanks!

**Comment by simison** [comment]
— to check at some point; https://sendgrid.com/blog/5-ways-check-sending-reputation/
